def balance(file_path: str) -> None: ...
def edit_record(file_path: str) -> None: ...
def search_record(file_path: str) -> None: ...


def add_record(file_path: str) -> None: ...


"""with open(file_path, "w") as file:
        file.write()"""
